### ISSUE TITLE
Unable to use the plugin

### ISSUE THREAD

**Issue by senkielvtars** [concerto-addons/concerto_template_scheduling#17]
Hello,

I've been trying to use the template scheduling module to display various content and to protect our screen from plasma burnout. The problem is, that every time I activate the plugin, I'm not able to view my screens anymore. I'm getting the following error message with every screens:

!500
Something went wrong. Rest assured, you have been assigned 0% of the blame.
Sometimes a strategic retreat is the best option.

As soon as I deactivate the plugin all screens are functioning again without a problem. 

**I'm using the Concerto 2 VM Image (.ova) on a Virtualbox machine (Debian)**

I would be grateful if you could help me.

Cheers

**Comment by augustf** [comment]
Hi-you'll want to post your issue to our community mailing list (concerto-digital-signage@googlegroups.com or via web at https://groups.google.com/forum/#!topic/concerto-digital-signage) to get the maximum number of replies to your issue. When you do so, please include the full stack trace from your error log (usually located at /usr/share/concerto/log/production.log).
