### ISSUE TITLE
handle non-english datetimes

### ISSUE THREAD

**Issue by mfrederickson** [concerto-addons/concerto_template_scheduling#23]

**Comment by mfrederickson** [comment]
When the is_effective? method runs to determine if the scheduled screen template is active, it is using the local/OS timezone instead of the timezone specified in the settings or the timezone specified for the screen.  In this example below, the TZ for the OS is AKDT, GMT-8, for the screen and settings is CST, GMT-5.
```
IS_EFFECTIVE?
Clock.time = 2018-03-15 17:01:42 -0800
self.start_time = 2018-03-15 06:30:00 -0500

IS_EFFECTIVE?
Clock.time = 2018-03-15 17:01:42 -0800
self.start_time = 2018-03-15 17:00:00 -0500
```

![selection_346](https://user-images.githubusercontent.com/473165/37498432-2b6c8b20-2873-11e8-9c30-c6b15ad83b96.png)

**Comment by Xeondile** [comment]
@mfrederickson I found my change file for fixing this issue. Hope this will help. I also working with the correct timezone.

[TimeZone Fix with language fix.txt](https://github.com/concerto-addons/concerto_template_scheduling/files/1818398/TimeZone.Fix.with.language.fix.txt)
